version: '3.7'

services:
  web:
    build:
      context: ..
      dockerfile: docker/node.Dockerfile
      args:
        SERVICE: web
    ports:
      - 3000:3000
  employees:
    build:
      context: ..
      dockerfile: docker/node.Dockerfile
      args:
        SERVICE: employees
    ports:
      - 3001:3001
  schedule:
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
      args:
        SERVICE: schedule
    ports:
      - 3002:3002